import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const exists=p=>fs.existsSync(path.join(root,p));
const fail=m=>{throw new Error(m)};
const requireMarkers=(name,text,markers)=>markers.forEach(m=>{if(!text.includes(m))fail(`${name}: missing ${m}`)});
const tools=read('src/lib/image-tools.ts');
const ids=[...tools.matchAll(/id:'([^']+)'/g)].map(m=>m[1]);
if(ids.length!==30)fail(`Expected 30 tools, found ${ids.length}`);
if(new Set(ids).size!==30)fail('Duplicate tool IDs found');
if(exists('src/app/bot/page.tsx')||exists('src/components/AjnBot.tsx')||exists('src/app/api/ajn-bot/route.ts'))fail('Legacy assistant source still exists');
const allSource=[];
function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())walk(f);else allSource.push(f)}}
walk(path.join(root,'src'));
for(const f of allSource){if(!/\.(ts|tsx)$/.test(f))continue;const t=fs.readFileSync(f,'utf8');if(/GEMINI_API_KEY|GEMINI_MODEL|NEXT_PUBLIC_GEMINI/i.test(t))fail(`Legacy environment reference found in ${path.relative(root,f)}`);if(/\b(TODO|FIXME|NOT\s+IMPLEMENTED|COMING\s+SOON)\b/i.test(t))fail(`Pending marker found in ${path.relative(root,f)}`)}
requireMarkers('tool engine',read('src/lib/image-engine.ts'),['export async function compressImage','targetBytes','pixelsFromPhysical','signature-remove-bg','remove-metadata','change-bg']);
requireMarkers('editor downloads',read('src/components/ImageEditor.tsx'),['Download','Preview','Share','Process another']);
requireMarkers('SEO',read('src/lib/seo.ts'),["'max-image-preview': 'large'",'openGraph','summary_large_image']);
requireMarkers('sitemap',read('src/app/sitemap.ts'),['IMAGE_TOOLS.map','SITE_URL']);
requireMarkers('image sitemap',read('src/app/image-sitemap.xml/route.ts'),['image:image','image:loc']);
requireMarkers('robots',read('src/app/robots.ts'),['sitemap.xml','image-sitemap.xml']);
requireMarkers('homepage',read('src/app/page.tsx'),['Explore all 30 image tools','Every tool, clearly listed','AJN PDF','Popular image tools']);
requireMarkers('logo',read('src/components/Shell.tsx'),['/brand/ajn-buzz-logo.png']);
const pkg=JSON.parse(read('package.json'));if(pkg.version!=='6.2.0')fail(`version ${pkg.version}`);if(pkg.dependencies?.firebase||pkg.dependencies?.['firebase-admin'])fail('Firebase dependency found');
if(!exists('public/brand/ajn-buzz-logo.png'))fail('Previous AJN BUZZ logo missing');
if(!exists('src/app/seo-tools/[slug].svg/route.ts'))fail('SEO image route missing');
if(read('.env.example').includes('GEMINI_'))fail('Gemini environment remains');
const seller='google.com, pub-4495802176396975, DIRECT, f08c47fec0942fa0';if(read('public/ads.txt').trim()!==seller||read('public/app-ads.txt').trim()!==seller)fail('ads.txt mismatch');
console.log(`PASS: exactly ${ids.length} focused public image tools`);
console.log('PASS: legacy assistant integration removed');
console.log('PASS: previous AJN BUZZ logo retained');
console.log('PASS: all core image workflows and download actions retained');
console.log('PASS: SEO metadata, web sitemap and image sitemap wired');
console.log('PASS: AJN PDF promotion retained as separate cross-product card');
console.log('PASS: production source verification complete');
